---
- name: EX467 Test
  hosts: all
  gather_facts: false

  tasks:
    - name: Show hostname
      ansible.builtin.command: hostname
      register: host_out

    - name: Display hostname
      ansible.builtin.debug:
        var: host_out.stdout
